name: Build and deploy PHP app to Azure Web App - adogheproject

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'azure-php-deploy'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if needed
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer install --prefer-dist --no-progress

      - name: Zip app for deployment
        run: |
          mkdir artifact
          zip -r artifact/release.zip . -x ".git/*"

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: artifact/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact
        run: unzip release.zip -d deploy-dir

      - name: Wait to avoid SCM restart conflict
        run: sleep 20

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'adogheproject'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy-dir
